config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  post '/room' => 'room#create', as: :rooms
  post '/message' => 'room#create_message', as: :messages
  get '/:room_id' => "pages#index", as: :room_show
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :room, class_name: "Room", foreign_key: "room_id"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :genToken  
  after_update :genToken 

  has_many :authored_messages, class_name: "Message", foreign_key: "author_id"
  def genToken 
    self.cabletoken = BCrypt::Password.create("self.id.to_s + self.encrypted_password")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :add_token  
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def add_token 
        if user_signed_in?
            @ctoken = current_user.cabletoken 
            @uid = current_user.id
        else
            @ctoken = nil
            @uid = nil
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @room = Room.new
    @rooms = Room.all
    if params[:room_id].present? 
      @id = params[:room_id]
      if Room.exists?(@id)
        @croom = Room.find(@id)
        @messages = Room.find(@id).messages
        @message = Message.new
      end
    end
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
    def create 
        p params
        @room = Room.create(room_params)
        if @room.save
            ActionCable.server.broadcast "main_channel", {room: @room}
            p @room 
        else
            p "Failure"
        end
    end 

    def show 
        @room = Room.new
        @rooms = Room.all
        @messages = Room.find(params[:room_id]).messages
        @message = Room.new
    end

    def create_message
        @message = Message.create(msg_params)
        if @message.save 
            ActionCable.server.broadcast "message_channel_#{@message.room_id}", {message: @message , user: User.find(@message.author_id)}
            p 'Works'  
        else 
            p 'doesnt not work'
        end
    end

    private 
    def room_params
        params.require(:room).permit(:name)
    end

    def msg_params 
        params.require(:message).permit(:content,:author_id,:room_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat bot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-8 px-5 ">
      <div  id="ctoken" data-uid = <%=@uid%>  data-ctoken = <%=@ctoken%> >

      
      <%= yield %>

      </div>
    </main>
  </body>
</html>

app/views/pages/_loggedout.html.erb
<div class="col-span-1">
    <span>Log in here!</span>
    <br><br>
    <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-1 px-1 rounded">
      <%= link_to "Log in" , new_user_session_url %>
    </button>
    <div data-main-id="1"></div>
  </div>

app/views/pages/_msg.html.erb
<% messages.includes(:author).each do |message|%>
<% if message.author_id == current_user.id %>
  <div class="flex justify-end mb-4">
    <div class="message-box sent p-2">
      <p class="text-xs"><%= message.content %></p>
  </div>
</div>
<%else%>
<div class="flex justify-start mb-4">
  <div class="message-container">
    <p class="author text-sm text-gray-500 pl-6"><%= message.author.username %></p>
  <div class="message-box received p-2">
      <p class="text-xs"><%= message.content %></p>
  </div>
</div>
</div>
<%end%>
<% end  %>

app/views/pages/_msg_form.html.erb
<%= form_with model: message do |form| %>

<%= form.hidden_field :room_id, value: @croom.id if @croom %>
<%= form.hidden_field :author_id, value: @current_user.id %>
<%= form.text_field :content %>
<%= form.submit %>
<%end %>

app/views/pages/_room_form.html.erb
<%= form_with model: room do |form| %>
<%= form.text_field :name %>
<br>
<%= form.submit %>
<%end %>
<br>

app/views/pages/_room_list.html.erb
Rooms
<br>
<div >
<% rooms.each do |room|%>
<div class="group">
  <ul id="room-list">
    <li><p class="text-gray-500 group-hover:text-red-500"><%= link_to room.name , room_show_url(room.id) %></p></li>
  </ul> 
</div>
  <%end%>
</div>
<br>

app/views/pages/index.html.erb
<div id="main-header" class="grid grid-cols-2" data-room-id= <%= params[:room_id] || 0 %> >
  <% if user_signed_in? %>
    <div class="col-span-1">
      <% if params[:room_id].present? && @croom.present?%>
        <h1> <%= @croom.name%> Room</h1>
        <% end %>

      <%= render partial: 'room_form' , locals: { room: @room } %>
      <%= render partial: 'room_list' , locals: { rooms: @rooms } %>
        <%= button_to "Log out" , destroy_user_session_path, method: :delete,class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-1 px-1 rounded" %>
    </div>
    <div class="col-span-1">
  <div id="this" class=" chat-main   overflow-auto px-2">
      <div id="chat-content">
        <% if params[:room_id].present? && @croom.present? %>
        <%= render partial: 'msg' , locals: {messages: @messages} %>
        <% end %> 
      </div>
    </div>

    <%= render partial: 'msg_form' , locals: {message: @message} %>
  </div>
    <% else %>
      <%= render 'loggedout' %>
        <% end %>
</div>